services:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    cpus: 0.5
    mem_limit: 512m
    volumes:
      - .stack-data/data:/data

  frontend:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    cpus: 0.5
    mem_limit: 512m
    depends_on:
      - backend
